apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: myapp-pipelinerun
spec:
  pipelineRef:
    name: build-and-deploy-myapp
  resources:
    - name: source
      resourceSpec:
        type: git
        params:
          - name: revision
            value: master
          - name: url
            value: https://github.com/ncskier/myapp
    - name: image
      resourceSpec:
        type: image
        params:
          - name: url
            value: localhost:5000/myapp
